name: '️ Migration repo'
description: 'Request a new repository.'
title: '️ Repository Request: '
labels:
  - 'repo-request'
  - 'issue-ops'
projects: 'wulfland/19'
assignees:
  - wulfland

body:
  - type: input
    id: name
    attributes:
      label: 'Name'
      description: 'Name of the repository in lower-case and kebab casing.'
      placeholder: 'your-name-kebab'
    validations:
      required: true
  
  - type: dropdown
    id: department
    attributes:
      label: 'Department'
      description: 'Pick your department. It will be used as a prefix for the repository name.'
      multiple: false
      options:
        - dep1
        - dep2
      default: 0
    validations:
      required: true
  
  - type: input  # This line defines the new text box
    id: additional_info  # Unique identifier for the text box
    attributes:
      label: 'Additional Information (Optional)'  # Label displayed to user
      description: 'Provide any additional details relevant to your request.'  # Explanation for the text box
      placeholder: 'e.g., Specific functionalities, references'  # Placeholder text to guide users