name: '🗒️ Migration repo'
description: 'Request a new repository.'
title: '🗒️ Repository Request: '
labels:
  - 'repo-request'
  - 'issue-ops'
projects: 'wulfland/19'
assignees:
  - wulfland

body:
  - type: input
    id: name
    attributes:
      label: 'Name'
      description: 'Name of the repository in lower-case and kebab casing.'
      placeholder: 'your-name-kebab'
    validations:
      required: true

  - type: input
    id: picture
    attributes:
      label: Attach a Picture (optional)
      description: If a picture helps illustrate the issue, please upload one here.
      type: image 
  
  - type: dropdown
    id: department
    attributes:
      label: 'Department'
      description: 'Pick your department. It will be used as a prefix for the repository name.'
      multiple: false
      options:
        - dep1
        - dep2
      default: 0
    validations:
      required: true
 # This specifies the input type as image


  